### ISSUE TITLE
Bouncing

### ISSUE THREAD

**Issue by Tessaira** [Tessaira/Ballistic-iwag#1]
Bouncing material of ball is not sufficient, therefore, a code is required.
The ball is supposed to bounce off the platform in random angles rather than a constant 90° up.

**Comment by Tessaira** [comment]
reference script for this issue is [Ball.cs](https://github.com/Tessaira/BouncyBall-iwag/blob/master/Assets/MyGame/Scripts/Ball.cs)

**Comment by smeerws** [comment]
See pull request

**Comment by Tessaira** [comment]
Thank you! Issue is now fixed.
